In [67]:
path = "/home/santiagovargas/dev/CancerImaging/CancerImaging/images/test images/"

In [86]:
import os
import numpy as np
from PIL import Image
from PIL import ImageFilter
from joblib import load

In [70]:
files = os.listdir(path)
print(files)
labels = np.zeros(len(files))
labels[4] = 1
labels[7] = 1
print(labels)

['IMG_0733.JPG', 'IMG_0768.JPG', 'IMG_0729.JPG', 'IMG_0748.JPG', 'IMG_0763.JPG', 'IMG_0769.JPG', 'IMG_0728.JPG', 'IMG_0764.JPG', 'IMG_0767.JPG', 'IMG_0734.JPG', 'IMG_0765.JPG', 'IMG_0745.JPG', 'IMG_0750.JPG', 'IMG_0749.JPG', 'IMG_0735.JPG', 'IMG_0746.JPG', 'IMG_0730.JPG', 'IMG_0759.JPG', 'IMG_0766.JPG']
[0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [71]:
files



['IMG_0733.JPG',
 'IMG_0768.JPG',
 'IMG_0729.JPG',
 'IMG_0748.JPG',
 'IMG_0763.JPG',
 'IMG_0769.JPG',
 'IMG_0728.JPG',
 'IMG_0764.JPG',
 'IMG_0767.JPG',
 'IMG_0734.JPG',
 'IMG_0765.JPG',
 'IMG_0745.JPG',
 'IMG_0750.JPG',
 'IMG_0749.JPG',
 'IMG_0735.JPG',
 'IMG_0746.JPG',
 'IMG_0730.JPG',
 'IMG_0759.JPG',
 'IMG_0766.JPG']

In [118]:
image_vector_256 = []
image_vector_128 = []

for i in files_img:
    #convert to single channel
    temp1 = Image.open(path + files_img[0]).convert('L')
    temp = temp.crop((800,800,800 + 1000,800 + 1000))
    #standardize
    temp = Image.fromarray((temp - np.mean(temp) / np.std(temp)).astype(np.uint8), 'L')
    #gaussian blur
    temp = temp.filter(ImageFilter.GaussianBlur(radius=6))
    
 
    
    img256 = temp.resize((256, 256), Image.ANTIALIAS)
    img128 = temp.resize((128, 128), Image.ANTIALIAS)

    image_vector_256.append(np.array(img256).flatten())
    image_vector_128.append(np.array(img128).flatten())
    
temp1.show()
img256.show()

/home/santiagovargas/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


Example Transformation on a single image


In [113]:
image_vector_256 = np.array(image_vector_256)
image_vector_128 = np.array(image_vector_128)



svm = load('/home/santiagovargas/dev/CancerImaging/CancerImaging/Trial_Models/svm_2019-7-26-9-9-22.pkl') 
sgd_1 = load('/home/santiagovargas/dev/CancerImaging/CancerImaging/Trial_Models/sgd_2019-7-26-9-23-29.pkl')
sgd_2 = load('/home/santiagovargas/dev/CancerImaging/CancerImaging/Trial_Models/sgd_2019-7-26-9-20-4.pkl')

#nn_1 = 
#cnn_1 =

(len(image_vector_128)-2)/len(image_vector_128)

/home/santiagovargas/.local/lib/python3.5/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator SVC from version 0.20.0 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/santiagovargas/.local/lib/python3.5/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator SGDClassifier from version 0.20.0 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


0.8888888888888888

In [115]:
svm.predict(image_vector_256)
#svm.predict_prob(image_vector_256)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [111]:
sgd_1.predict(image_vector_128)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [112]:
sgd_2.predict(image_vector_128)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])