In [2]:
import cv2
import numpy as np 
from matplotlib import pyplot as plt
import argparse
from sklearn.model_selection import train_test_split

In [3]:
#read images
negative = cv2.imread("margin_rodent.jpg")
positive = cv2.imread("tumor_human.jpg")

bw_negative = cv2.cvtColor(negative, cv2.COLOR_BGR2GRAY)
bw_positive = cv2.cvtColor(positive, cv2.COLOR_BGR2GRAY)
print(type(bw_negative))

<class 'numpy.ndarray'>


In [6]:
cube_size_gray = np.array([negative.shape[0]/16, negative.shape[1]/16,1])
cube_size_gray = cube_size_gray.astype("int")
print(cube_size_gray)

[69 86  1]


In [7]:
random_index = np.arange(69*86*2)
np.random.shuffle(random_index)

image_vector = np.concatenate((bw_negative, bw_positive), axis=1)
temp = np.zeros(69*86)
temp1 = np.zeros(69*86) + 1
results_vector = np.concatenate((temp, temp1))

test_ind = random_index[0:int(len(random_index)*0.2)]
train_ind = random_index[int(len(random_index)*0.2):-1]

print(test_ind)
print(train_ind)

[1561 5004 8884 ... 2387 9661  570]
[5977 8936 8448 ... 7328 4589 6689]


In [8]:
transform_train = []
transform_test = []

for i in test_ind:
    
for i in train_ind:

vals_ind_train = results_vector[train_ind]
vals_ind_test = results_vector[test_ind]
print(vals_ind_test)

[0. 0. 1. ... 0. 1. 0.]
